--- # Starting the PEERS
- hosts: 9.42.137.193
  user: vagrant
  sudo: yes
  gather_facts: no
  vars_prompt:
  - name: peers
    prompt: Number of peers
    default: 4
    private: no
  vars:
    REST_PORT: 7050
    USE_PORT: 30001
    CA_PORT: 7054
    PEER_gRPC: 7051
    PBFT_MODE: batch
    CONSENSUS_MODE: pbft
  tasks:
  - name: Getting the docker ip address
    action: shell ifconfig docker0 | grep "inet" | awk '{print $2}' | cut -d ':' -f 2
    register: ip
    tags:
    - always
  - name: Getting docker port
    action: shell netstat -tunlp | grep docker | awk '{print $4'} | cut -d ":" -f 4
    register: port
    tags:
    - always
  - name: pulling the baseimage
    action: shell docker pull rameshthoomu/baseimage:latest
    notify: tagging
    tags:
    - always
  - name: pulling hyperledger/fabric-peer
    docker_image:
      name: hyperledger/fabric-peer
      repository: hyperledger/fabric-peer
    tags:
    - always
  - name: pulling hyperledger/fabric-membersrvc
    docker_image:
      name: hyperledger/fabric-membersrvc
      repository: hyperledger/fabric-membersrvc
    tags:
    - always
  - shell: sed -i.bak '/^DOCKER_OPTS=/{h;s|=.*|=\"'"${DOCKER_OPTS}"'\"|};${x;/^$/{s||DOCKER_OPTS=\"'"${DOCKER_OPTS}"'\"|;H};x}' /etc/default/docker 
  - name: Removing docker containers
    action: shell docker rm -f $(docker ps -aq)
    ignore_errors: yes
    tags:
    - always
  - include: securityenabled.yml
    tags:
    - enable
  - include: securitydisabled.yml
    tags:
    - disable
  handlers:
  - name: tagging
    action: shell docker tag rameshthoomu/baseimage:latest hyperledger/fabric-baseimage:latest

